---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by netdex.
--- DateTime: 11/16/2020 10:47 AM
---

usb = luausb.create({ id = 0, type = "storage" })

while true do
    usb.delay(1000)
end
