name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    
    - name: Generate build information
      id: build
      shell: bash
      run: |
        echo "::set-output name=artifact_name::${{ github.event.repository.name }}-r$(git rev-parse --short HEAD)-${{ github.run_id }}"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build.outputs.artifact_name }}
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
